# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r reqirement.txt
          pip install --upgrade pip

      - name: test application with pytest
        run: |
          source .venv/bin/activate
          pytest

      - name: run the application
        run: |
          source .venv/bin/activate
          fastapi dev app\api\api_endpoint.py
